services:
  chatmepls.pg.db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: chatmepls
      POSTGRES_PASSWORD: chatmepls
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  
  chatmepls.user.api:
    image: chatmepls.user.api
    build:
      context: .
      dockerfile: ChatMePls.User.Api/Dockerfile
